name       : perl-locale-maketext
version    : '1.32'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/T/TO/TODDR/Locale-Maketext-1.32.tar.gz : 9cf49f5cb3db81a2db0459c7ddaa824edc0533ba233dc64b062b8f2f022d55d7
homepage   : https://metacpan.org/pod/Locale::Maketext
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Locale::Maketext - framework for localization
description: |
    It is a common feature of applications (whether run directly, or via the Web) for them to be "localized" -- i.e., for them to a present an English interface to an English-speaker, a German interface to a German-speaker, and so on for all languages it's programmed with. Locale::Maketext is a framework for software localization; it provides you with the tools for organizing and accessing the bits of text and text-processing code that you need for producing localized applications.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
