name       : perl-locale-maketext
version    : 1.28
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/T/TO/TODDR/Locale-Maketext-1.28.tar.gz : 578493b483e81159a1ad2bb5f9747fa74542b6f3fa777e7fd4b6e199a065f7e9
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Locale::Maketext - framework for localization
description: |
    Locale::Maketext - framework for localization
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
